# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vNerve/bilibili/live/message.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from vNerve.bilibili.live import room_message_pb2 as vNerve_dot_bilibili_dot_live_dot_room__message__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='vNerve/bilibili/live/message.proto',
  package='vNerve.bilibili.live',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\"vNerve/bilibili/live/message.proto\x12\x14vNerve.bilibili.live\x1a\'vNerve/bilibili/live/room_message.proto\"b\n\x07Message\x12\x11\n\ttimestamp\x18\x01 \x01(\x04\x12\x39\n\x0croom_message\x18\x02 \x01(\x0b\x32!.vNerve.bilibili.live.RoomMessageH\x00\x42\t\n\x07payloadb\x06proto3'
  ,
  dependencies=[vNerve_dot_bilibili_dot_live_dot_room__message__pb2.DESCRIPTOR,])




_MESSAGE = _descriptor.Descriptor(
  name='Message',
  full_name='vNerve.bilibili.live.Message',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='vNerve.bilibili.live.Message.timestamp', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='room_message', full_name='vNerve.bilibili.live.Message.room_message', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='payload', full_name='vNerve.bilibili.live.Message.payload',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=101,
  serialized_end=199,
)

_MESSAGE.fields_by_name['room_message'].message_type = vNerve_dot_bilibili_dot_live_dot_room__message__pb2._ROOMMESSAGE
_MESSAGE.oneofs_by_name['payload'].fields.append(
  _MESSAGE.fields_by_name['room_message'])
_MESSAGE.fields_by_name['room_message'].containing_oneof = _MESSAGE.oneofs_by_name['payload']
DESCRIPTOR.message_types_by_name['Message'] = _MESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Message = _reflection.GeneratedProtocolMessageType('Message', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGE,
  '__module__' : 'vNerve.bilibili.live.message_pb2'
  # @@protoc_insertion_point(class_scope:vNerve.bilibili.live.Message)
  })
_sym_db.RegisterMessage(Message)


# @@protoc_insertion_point(module_scope)
