# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vNerve/bilibili/bilibili_info.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='vNerve/bilibili/bilibili_info.proto',
  package='vNerve.bilibili',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n#vNerve/bilibili/bilibili_info.proto\x12\x0fvNerve.bilibili\"1\n\x1aGetAllBilibiliInfosRequest\x12\x13\n\x0bstatic_only\x18\x01 \x01(\x08\"?\n\x1bGetBilibiliInfoByUidRequest\x12\x0b\n\x03uid\x18\x01 \x01(\r\x12\x13\n\x0bstatic_only\x18\x02 \x01(\x08\"K\n\x12\x42ilibiliCollection\x12\x35\n\x0e\x62ilibili_infos\x18\x01 \x03(\x0b\x32\x1d.vNerve.bilibili.BilibiliInfo\"\xc9\x03\n\x0c\x42ilibiliInfo\x12\x0b\n\x03uid\x18\x01 \x01(\r\x12\x0c\n\x04uuid\x18\x02 \x01(\t\x12\r\n\x05uname\x18\x03 \x01(\t\x12\x0f\n\x07room_id\x18\x04 \x01(\r\x12\x10\n\x08\x66ollower\x18\x05 \x01(\r\x12 \n\x18\x66ollower_daily_increment\x18\x06 \x01(\x05\x12\x12\n\nroom_title\x18\x07 \x01(\t\x12\x30\n\x0blive_status\x18\x08 \x01(\x0e\x32\x1b.vNerve.bilibili.LiveStatus\x12\x12\n\npopularity\x18\t \x01(\r\x12\x11\n\trank_area\x18\n \x01(\r\x12\x13\n\x0b\x64\x65scription\x18\x0b \x01(\t\x12\x13\n\x0broom_notice\x18\x0c \x01(\t\x12\x12\n\navatar_url\x18\r \x01(\t\x12\x18\n\x10\x62\x61nner_image_url\x18\x0e \x01(\t\x12\x13\n\x0bvideo_count\x18\x0f \x01(\r\x12\x19\n\x11video_total_views\x18\x10 \x01(\r\x12\x13\n\x0bguard_count\x18\x11 \x01(\r\x12\x14\n\x0cguard_level1\x18\x12 \x01(\r\x12\x14\n\x0cguard_level2\x18\x13 \x01(\r\x12\x14\n\x0cguard_level3\x18\x14 \x01(\r*=\n\nLiveStatus\x12\r\n\tPREPARING\x10\x00\x12\x08\n\x04LIVE\x10\x01\x12\t\n\x05ROUND\x10\x02\x12\x0b\n\x07\x43UT_OFF\x10\x03\x32\xd8\x01\n\x08\x42ilibili\x12g\n\x13GetAllBilibiliInfos\x12+.vNerve.bilibili.GetAllBilibiliInfosRequest\x1a#.vNerve.bilibili.BilibiliCollection\x12\x63\n\x14GetBilibiliInfoByUid\x12,.vNerve.bilibili.GetBilibiliInfoByUidRequest\x1a\x1d.vNerve.bilibili.BilibiliInfob\x06proto3'
)

_LIVESTATUS = _descriptor.EnumDescriptor(
  name='LiveStatus',
  full_name='vNerve.bilibili.LiveStatus',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='PREPARING', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LIVE', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ROUND', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CUT_OFF', index=3, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=709,
  serialized_end=770,
)
_sym_db.RegisterEnumDescriptor(_LIVESTATUS)

LiveStatus = enum_type_wrapper.EnumTypeWrapper(_LIVESTATUS)
PREPARING = 0
LIVE = 1
ROUND = 2
CUT_OFF = 3



_GETALLBILIBILIINFOSREQUEST = _descriptor.Descriptor(
  name='GetAllBilibiliInfosRequest',
  full_name='vNerve.bilibili.GetAllBilibiliInfosRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='static_only', full_name='vNerve.bilibili.GetAllBilibiliInfosRequest.static_only', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=56,
  serialized_end=105,
)


_GETBILIBILIINFOBYUIDREQUEST = _descriptor.Descriptor(
  name='GetBilibiliInfoByUidRequest',
  full_name='vNerve.bilibili.GetBilibiliInfoByUidRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uid', full_name='vNerve.bilibili.GetBilibiliInfoByUidRequest.uid', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='static_only', full_name='vNerve.bilibili.GetBilibiliInfoByUidRequest.static_only', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=107,
  serialized_end=170,
)


_BILIBILICOLLECTION = _descriptor.Descriptor(
  name='BilibiliCollection',
  full_name='vNerve.bilibili.BilibiliCollection',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='bilibili_infos', full_name='vNerve.bilibili.BilibiliCollection.bilibili_infos', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=172,
  serialized_end=247,
)


_BILIBILIINFO = _descriptor.Descriptor(
  name='BilibiliInfo',
  full_name='vNerve.bilibili.BilibiliInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uid', full_name='vNerve.bilibili.BilibiliInfo.uid', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='uuid', full_name='vNerve.bilibili.BilibiliInfo.uuid', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='uname', full_name='vNerve.bilibili.BilibiliInfo.uname', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='room_id', full_name='vNerve.bilibili.BilibiliInfo.room_id', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='follower', full_name='vNerve.bilibili.BilibiliInfo.follower', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='follower_daily_increment', full_name='vNerve.bilibili.BilibiliInfo.follower_daily_increment', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='room_title', full_name='vNerve.bilibili.BilibiliInfo.room_title', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='live_status', full_name='vNerve.bilibili.BilibiliInfo.live_status', index=7,
      number=8, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='popularity', full_name='vNerve.bilibili.BilibiliInfo.popularity', index=8,
      number=9, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rank_area', full_name='vNerve.bilibili.BilibiliInfo.rank_area', index=9,
      number=10, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='description', full_name='vNerve.bilibili.BilibiliInfo.description', index=10,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='room_notice', full_name='vNerve.bilibili.BilibiliInfo.room_notice', index=11,
      number=12, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='avatar_url', full_name='vNerve.bilibili.BilibiliInfo.avatar_url', index=12,
      number=13, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='banner_image_url', full_name='vNerve.bilibili.BilibiliInfo.banner_image_url', index=13,
      number=14, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='video_count', full_name='vNerve.bilibili.BilibiliInfo.video_count', index=14,
      number=15, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='video_total_views', full_name='vNerve.bilibili.BilibiliInfo.video_total_views', index=15,
      number=16, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='guard_count', full_name='vNerve.bilibili.BilibiliInfo.guard_count', index=16,
      number=17, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='guard_level1', full_name='vNerve.bilibili.BilibiliInfo.guard_level1', index=17,
      number=18, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='guard_level2', full_name='vNerve.bilibili.BilibiliInfo.guard_level2', index=18,
      number=19, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='guard_level3', full_name='vNerve.bilibili.BilibiliInfo.guard_level3', index=19,
      number=20, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=250,
  serialized_end=707,
)

_BILIBILICOLLECTION.fields_by_name['bilibili_infos'].message_type = _BILIBILIINFO
_BILIBILIINFO.fields_by_name['live_status'].enum_type = _LIVESTATUS
DESCRIPTOR.message_types_by_name['GetAllBilibiliInfosRequest'] = _GETALLBILIBILIINFOSREQUEST
DESCRIPTOR.message_types_by_name['GetBilibiliInfoByUidRequest'] = _GETBILIBILIINFOBYUIDREQUEST
DESCRIPTOR.message_types_by_name['BilibiliCollection'] = _BILIBILICOLLECTION
DESCRIPTOR.message_types_by_name['BilibiliInfo'] = _BILIBILIINFO
DESCRIPTOR.enum_types_by_name['LiveStatus'] = _LIVESTATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetAllBilibiliInfosRequest = _reflection.GeneratedProtocolMessageType('GetAllBilibiliInfosRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETALLBILIBILIINFOSREQUEST,
  '__module__' : 'vNerve.bilibili.bilibili_info_pb2'
  # @@protoc_insertion_point(class_scope:vNerve.bilibili.GetAllBilibiliInfosRequest)
  })
_sym_db.RegisterMessage(GetAllBilibiliInfosRequest)

GetBilibiliInfoByUidRequest = _reflection.GeneratedProtocolMessageType('GetBilibiliInfoByUidRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETBILIBILIINFOBYUIDREQUEST,
  '__module__' : 'vNerve.bilibili.bilibili_info_pb2'
  # @@protoc_insertion_point(class_scope:vNerve.bilibili.GetBilibiliInfoByUidRequest)
  })
_sym_db.RegisterMessage(GetBilibiliInfoByUidRequest)

BilibiliCollection = _reflection.GeneratedProtocolMessageType('BilibiliCollection', (_message.Message,), {
  'DESCRIPTOR' : _BILIBILICOLLECTION,
  '__module__' : 'vNerve.bilibili.bilibili_info_pb2'
  # @@protoc_insertion_point(class_scope:vNerve.bilibili.BilibiliCollection)
  })
_sym_db.RegisterMessage(BilibiliCollection)

BilibiliInfo = _reflection.GeneratedProtocolMessageType('BilibiliInfo', (_message.Message,), {
  'DESCRIPTOR' : _BILIBILIINFO,
  '__module__' : 'vNerve.bilibili.bilibili_info_pb2'
  # @@protoc_insertion_point(class_scope:vNerve.bilibili.BilibiliInfo)
  })
_sym_db.RegisterMessage(BilibiliInfo)



_BILIBILI = _descriptor.ServiceDescriptor(
  name='Bilibili',
  full_name='vNerve.bilibili.Bilibili',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=773,
  serialized_end=989,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetAllBilibiliInfos',
    full_name='vNerve.bilibili.Bilibili.GetAllBilibiliInfos',
    index=0,
    containing_service=None,
    input_type=_GETALLBILIBILIINFOSREQUEST,
    output_type=_BILIBILICOLLECTION,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetBilibiliInfoByUid',
    full_name='vNerve.bilibili.Bilibili.GetBilibiliInfoByUid',
    index=1,
    containing_service=None,
    input_type=_GETBILIBILIINFOBYUIDREQUEST,
    output_type=_BILIBILIINFO,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_BILIBILI)

DESCRIPTOR.services_by_name['Bilibili'] = _BILIBILI

# @@protoc_insertion_point(module_scope)
