// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: vNerve/bilibili/bilibili_info.proto
#ifndef GRPC_vNerve_2fbilibili_2fbilibili_5finfo_2eproto__INCLUDED
#define GRPC_vNerve_2fbilibili_2fbilibili_5finfo_2eproto__INCLUDED

#include "vNerve/bilibili/bilibili_info.pb.h"

#include <functional>
#include <grpc/impl/codegen/port_platform.h>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace vNerve {
namespace bilibili {

class Bilibili final {
 public:
  static constexpr char const* service_full_name() {
    return "vNerve.bilibili.Bilibili";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status GetAllBilibiliInfos(::grpc::ClientContext* context, const ::vNerve::bilibili::GetAllBilibiliInfosRequest& request, ::vNerve::bilibili::BilibiliCollection* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::vNerve::bilibili::BilibiliCollection>> AsyncGetAllBilibiliInfos(::grpc::ClientContext* context, const ::vNerve::bilibili::GetAllBilibiliInfosRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::vNerve::bilibili::BilibiliCollection>>(AsyncGetAllBilibiliInfosRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::vNerve::bilibili::BilibiliCollection>> PrepareAsyncGetAllBilibiliInfos(::grpc::ClientContext* context, const ::vNerve::bilibili::GetAllBilibiliInfosRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::vNerve::bilibili::BilibiliCollection>>(PrepareAsyncGetAllBilibiliInfosRaw(context, request, cq));
    }
    virtual ::grpc::Status GetBilibiliInfoByUid(::grpc::ClientContext* context, const ::vNerve::bilibili::GetBilibiliInfoByUidRequest& request, ::vNerve::bilibili::BilibiliInfo* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::vNerve::bilibili::BilibiliInfo>> AsyncGetBilibiliInfoByUid(::grpc::ClientContext* context, const ::vNerve::bilibili::GetBilibiliInfoByUidRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::vNerve::bilibili::BilibiliInfo>>(AsyncGetBilibiliInfoByUidRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::vNerve::bilibili::BilibiliInfo>> PrepareAsyncGetBilibiliInfoByUid(::grpc::ClientContext* context, const ::vNerve::bilibili::GetBilibiliInfoByUidRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::vNerve::bilibili::BilibiliInfo>>(PrepareAsyncGetBilibiliInfoByUidRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      virtual void GetAllBilibiliInfos(::grpc::ClientContext* context, const ::vNerve::bilibili::GetAllBilibiliInfosRequest* request, ::vNerve::bilibili::BilibiliCollection* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetAllBilibiliInfos(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::vNerve::bilibili::BilibiliCollection* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void GetAllBilibiliInfos(::grpc::ClientContext* context, const ::vNerve::bilibili::GetAllBilibiliInfosRequest* request, ::vNerve::bilibili::BilibiliCollection* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void GetAllBilibiliInfos(::grpc::ClientContext* context, const ::vNerve::bilibili::GetAllBilibiliInfosRequest* request, ::vNerve::bilibili::BilibiliCollection* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void GetAllBilibiliInfos(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::vNerve::bilibili::BilibiliCollection* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void GetAllBilibiliInfos(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::vNerve::bilibili::BilibiliCollection* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      virtual void GetBilibiliInfoByUid(::grpc::ClientContext* context, const ::vNerve::bilibili::GetBilibiliInfoByUidRequest* request, ::vNerve::bilibili::BilibiliInfo* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetBilibiliInfoByUid(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::vNerve::bilibili::BilibiliInfo* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void GetBilibiliInfoByUid(::grpc::ClientContext* context, const ::vNerve::bilibili::GetBilibiliInfoByUidRequest* request, ::vNerve::bilibili::BilibiliInfo* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void GetBilibiliInfoByUid(::grpc::ClientContext* context, const ::vNerve::bilibili::GetBilibiliInfoByUidRequest* request, ::vNerve::bilibili::BilibiliInfo* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void GetBilibiliInfoByUid(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::vNerve::bilibili::BilibiliInfo* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void GetBilibiliInfoByUid(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::vNerve::bilibili::BilibiliInfo* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
    };
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    typedef class experimental_async_interface async_interface;
    #endif
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    async_interface* async() { return experimental_async(); }
    #endif
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::vNerve::bilibili::BilibiliCollection>* AsyncGetAllBilibiliInfosRaw(::grpc::ClientContext* context, const ::vNerve::bilibili::GetAllBilibiliInfosRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::vNerve::bilibili::BilibiliCollection>* PrepareAsyncGetAllBilibiliInfosRaw(::grpc::ClientContext* context, const ::vNerve::bilibili::GetAllBilibiliInfosRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::vNerve::bilibili::BilibiliInfo>* AsyncGetBilibiliInfoByUidRaw(::grpc::ClientContext* context, const ::vNerve::bilibili::GetBilibiliInfoByUidRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::vNerve::bilibili::BilibiliInfo>* PrepareAsyncGetBilibiliInfoByUidRaw(::grpc::ClientContext* context, const ::vNerve::bilibili::GetBilibiliInfoByUidRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status GetAllBilibiliInfos(::grpc::ClientContext* context, const ::vNerve::bilibili::GetAllBilibiliInfosRequest& request, ::vNerve::bilibili::BilibiliCollection* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::vNerve::bilibili::BilibiliCollection>> AsyncGetAllBilibiliInfos(::grpc::ClientContext* context, const ::vNerve::bilibili::GetAllBilibiliInfosRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::vNerve::bilibili::BilibiliCollection>>(AsyncGetAllBilibiliInfosRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::vNerve::bilibili::BilibiliCollection>> PrepareAsyncGetAllBilibiliInfos(::grpc::ClientContext* context, const ::vNerve::bilibili::GetAllBilibiliInfosRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::vNerve::bilibili::BilibiliCollection>>(PrepareAsyncGetAllBilibiliInfosRaw(context, request, cq));
    }
    ::grpc::Status GetBilibiliInfoByUid(::grpc::ClientContext* context, const ::vNerve::bilibili::GetBilibiliInfoByUidRequest& request, ::vNerve::bilibili::BilibiliInfo* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::vNerve::bilibili::BilibiliInfo>> AsyncGetBilibiliInfoByUid(::grpc::ClientContext* context, const ::vNerve::bilibili::GetBilibiliInfoByUidRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::vNerve::bilibili::BilibiliInfo>>(AsyncGetBilibiliInfoByUidRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::vNerve::bilibili::BilibiliInfo>> PrepareAsyncGetBilibiliInfoByUid(::grpc::ClientContext* context, const ::vNerve::bilibili::GetBilibiliInfoByUidRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::vNerve::bilibili::BilibiliInfo>>(PrepareAsyncGetBilibiliInfoByUidRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void GetAllBilibiliInfos(::grpc::ClientContext* context, const ::vNerve::bilibili::GetAllBilibiliInfosRequest* request, ::vNerve::bilibili::BilibiliCollection* response, std::function<void(::grpc::Status)>) override;
      void GetAllBilibiliInfos(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::vNerve::bilibili::BilibiliCollection* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void GetAllBilibiliInfos(::grpc::ClientContext* context, const ::vNerve::bilibili::GetAllBilibiliInfosRequest* request, ::vNerve::bilibili::BilibiliCollection* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void GetAllBilibiliInfos(::grpc::ClientContext* context, const ::vNerve::bilibili::GetAllBilibiliInfosRequest* request, ::vNerve::bilibili::BilibiliCollection* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void GetAllBilibiliInfos(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::vNerve::bilibili::BilibiliCollection* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void GetAllBilibiliInfos(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::vNerve::bilibili::BilibiliCollection* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      void GetBilibiliInfoByUid(::grpc::ClientContext* context, const ::vNerve::bilibili::GetBilibiliInfoByUidRequest* request, ::vNerve::bilibili::BilibiliInfo* response, std::function<void(::grpc::Status)>) override;
      void GetBilibiliInfoByUid(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::vNerve::bilibili::BilibiliInfo* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void GetBilibiliInfoByUid(::grpc::ClientContext* context, const ::vNerve::bilibili::GetBilibiliInfoByUidRequest* request, ::vNerve::bilibili::BilibiliInfo* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void GetBilibiliInfoByUid(::grpc::ClientContext* context, const ::vNerve::bilibili::GetBilibiliInfoByUidRequest* request, ::vNerve::bilibili::BilibiliInfo* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void GetBilibiliInfoByUid(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::vNerve::bilibili::BilibiliInfo* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void GetBilibiliInfoByUid(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::vNerve::bilibili::BilibiliInfo* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::vNerve::bilibili::BilibiliCollection>* AsyncGetAllBilibiliInfosRaw(::grpc::ClientContext* context, const ::vNerve::bilibili::GetAllBilibiliInfosRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::vNerve::bilibili::BilibiliCollection>* PrepareAsyncGetAllBilibiliInfosRaw(::grpc::ClientContext* context, const ::vNerve::bilibili::GetAllBilibiliInfosRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::vNerve::bilibili::BilibiliInfo>* AsyncGetBilibiliInfoByUidRaw(::grpc::ClientContext* context, const ::vNerve::bilibili::GetBilibiliInfoByUidRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::vNerve::bilibili::BilibiliInfo>* PrepareAsyncGetBilibiliInfoByUidRaw(::grpc::ClientContext* context, const ::vNerve::bilibili::GetBilibiliInfoByUidRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_GetAllBilibiliInfos_;
    const ::grpc::internal::RpcMethod rpcmethod_GetBilibiliInfoByUid_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status GetAllBilibiliInfos(::grpc::ServerContext* context, const ::vNerve::bilibili::GetAllBilibiliInfosRequest* request, ::vNerve::bilibili::BilibiliCollection* response);
    virtual ::grpc::Status GetBilibiliInfoByUid(::grpc::ServerContext* context, const ::vNerve::bilibili::GetBilibiliInfoByUidRequest* request, ::vNerve::bilibili::BilibiliInfo* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_GetAllBilibiliInfos : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetAllBilibiliInfos() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_GetAllBilibiliInfos() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetAllBilibiliInfos(::grpc::ServerContext* /*context*/, const ::vNerve::bilibili::GetAllBilibiliInfosRequest* /*request*/, ::vNerve::bilibili::BilibiliCollection* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetAllBilibiliInfos(::grpc::ServerContext* context, ::vNerve::bilibili::GetAllBilibiliInfosRequest* request, ::grpc::ServerAsyncResponseWriter< ::vNerve::bilibili::BilibiliCollection>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_GetBilibiliInfoByUid : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetBilibiliInfoByUid() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_GetBilibiliInfoByUid() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetBilibiliInfoByUid(::grpc::ServerContext* /*context*/, const ::vNerve::bilibili::GetBilibiliInfoByUidRequest* /*request*/, ::vNerve::bilibili::BilibiliInfo* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetBilibiliInfoByUid(::grpc::ServerContext* context, ::vNerve::bilibili::GetBilibiliInfoByUidRequest* request, ::grpc::ServerAsyncResponseWriter< ::vNerve::bilibili::BilibiliInfo>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_GetAllBilibiliInfos<WithAsyncMethod_GetBilibiliInfoByUid<Service > > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_GetAllBilibiliInfos : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_GetAllBilibiliInfos() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(0,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::vNerve::bilibili::GetAllBilibiliInfosRequest, ::vNerve::bilibili::BilibiliCollection>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::vNerve::bilibili::GetAllBilibiliInfosRequest* request, ::vNerve::bilibili::BilibiliCollection* response) { return this->GetAllBilibiliInfos(context, request, response); }));}
    void SetMessageAllocatorFor_GetAllBilibiliInfos(
        ::grpc::experimental::MessageAllocator< ::vNerve::bilibili::GetAllBilibiliInfosRequest, ::vNerve::bilibili::BilibiliCollection>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(0);
    #endif
      static_cast<::grpc_impl::internal::CallbackUnaryHandler< ::vNerve::bilibili::GetAllBilibiliInfosRequest, ::vNerve::bilibili::BilibiliCollection>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_GetAllBilibiliInfos() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetAllBilibiliInfos(::grpc::ServerContext* /*context*/, const ::vNerve::bilibili::GetAllBilibiliInfosRequest* /*request*/, ::vNerve::bilibili::BilibiliCollection* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* GetAllBilibiliInfos(
      ::grpc::CallbackServerContext* /*context*/, const ::vNerve::bilibili::GetAllBilibiliInfosRequest* /*request*/, ::vNerve::bilibili::BilibiliCollection* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* GetAllBilibiliInfos(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::vNerve::bilibili::GetAllBilibiliInfosRequest* /*request*/, ::vNerve::bilibili::BilibiliCollection* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_GetBilibiliInfoByUid : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_GetBilibiliInfoByUid() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(1,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::vNerve::bilibili::GetBilibiliInfoByUidRequest, ::vNerve::bilibili::BilibiliInfo>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::vNerve::bilibili::GetBilibiliInfoByUidRequest* request, ::vNerve::bilibili::BilibiliInfo* response) { return this->GetBilibiliInfoByUid(context, request, response); }));}
    void SetMessageAllocatorFor_GetBilibiliInfoByUid(
        ::grpc::experimental::MessageAllocator< ::vNerve::bilibili::GetBilibiliInfoByUidRequest, ::vNerve::bilibili::BilibiliInfo>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(1);
    #endif
      static_cast<::grpc_impl::internal::CallbackUnaryHandler< ::vNerve::bilibili::GetBilibiliInfoByUidRequest, ::vNerve::bilibili::BilibiliInfo>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_GetBilibiliInfoByUid() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetBilibiliInfoByUid(::grpc::ServerContext* /*context*/, const ::vNerve::bilibili::GetBilibiliInfoByUidRequest* /*request*/, ::vNerve::bilibili::BilibiliInfo* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* GetBilibiliInfoByUid(
      ::grpc::CallbackServerContext* /*context*/, const ::vNerve::bilibili::GetBilibiliInfoByUidRequest* /*request*/, ::vNerve::bilibili::BilibiliInfo* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* GetBilibiliInfoByUid(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::vNerve::bilibili::GetBilibiliInfoByUidRequest* /*request*/, ::vNerve::bilibili::BilibiliInfo* /*response*/)
    #endif
      { return nullptr; }
  };
  #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
  typedef ExperimentalWithCallbackMethod_GetAllBilibiliInfos<ExperimentalWithCallbackMethod_GetBilibiliInfoByUid<Service > > CallbackService;
  #endif

  typedef ExperimentalWithCallbackMethod_GetAllBilibiliInfos<ExperimentalWithCallbackMethod_GetBilibiliInfoByUid<Service > > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_GetAllBilibiliInfos : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetAllBilibiliInfos() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_GetAllBilibiliInfos() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetAllBilibiliInfos(::grpc::ServerContext* /*context*/, const ::vNerve::bilibili::GetAllBilibiliInfosRequest* /*request*/, ::vNerve::bilibili::BilibiliCollection* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_GetBilibiliInfoByUid : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetBilibiliInfoByUid() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_GetBilibiliInfoByUid() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetBilibiliInfoByUid(::grpc::ServerContext* /*context*/, const ::vNerve::bilibili::GetBilibiliInfoByUidRequest* /*request*/, ::vNerve::bilibili::BilibiliInfo* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetAllBilibiliInfos : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetAllBilibiliInfos() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_GetAllBilibiliInfos() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetAllBilibiliInfos(::grpc::ServerContext* /*context*/, const ::vNerve::bilibili::GetAllBilibiliInfosRequest* /*request*/, ::vNerve::bilibili::BilibiliCollection* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetAllBilibiliInfos(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetBilibiliInfoByUid : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetBilibiliInfoByUid() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_GetBilibiliInfoByUid() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetBilibiliInfoByUid(::grpc::ServerContext* /*context*/, const ::vNerve::bilibili::GetBilibiliInfoByUidRequest* /*request*/, ::vNerve::bilibili::BilibiliInfo* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetBilibiliInfoByUid(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_GetAllBilibiliInfos : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_GetAllBilibiliInfos() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(0,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetAllBilibiliInfos(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_GetAllBilibiliInfos() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetAllBilibiliInfos(::grpc::ServerContext* /*context*/, const ::vNerve::bilibili::GetAllBilibiliInfosRequest* /*request*/, ::vNerve::bilibili::BilibiliCollection* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* GetAllBilibiliInfos(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* GetAllBilibiliInfos(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_GetBilibiliInfoByUid : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_GetBilibiliInfoByUid() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(1,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetBilibiliInfoByUid(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_GetBilibiliInfoByUid() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetBilibiliInfoByUid(::grpc::ServerContext* /*context*/, const ::vNerve::bilibili::GetBilibiliInfoByUidRequest* /*request*/, ::vNerve::bilibili::BilibiliInfo* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* GetBilibiliInfoByUid(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* GetBilibiliInfoByUid(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetAllBilibiliInfos : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetAllBilibiliInfos() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler< ::vNerve::bilibili::GetAllBilibiliInfosRequest, ::vNerve::bilibili::BilibiliCollection>(std::bind(&WithStreamedUnaryMethod_GetAllBilibiliInfos<BaseClass>::StreamedGetAllBilibiliInfos, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_GetAllBilibiliInfos() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetAllBilibiliInfos(::grpc::ServerContext* /*context*/, const ::vNerve::bilibili::GetAllBilibiliInfosRequest* /*request*/, ::vNerve::bilibili::BilibiliCollection* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetAllBilibiliInfos(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::vNerve::bilibili::GetAllBilibiliInfosRequest,::vNerve::bilibili::BilibiliCollection>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetBilibiliInfoByUid : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetBilibiliInfoByUid() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler< ::vNerve::bilibili::GetBilibiliInfoByUidRequest, ::vNerve::bilibili::BilibiliInfo>(std::bind(&WithStreamedUnaryMethod_GetBilibiliInfoByUid<BaseClass>::StreamedGetBilibiliInfoByUid, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_GetBilibiliInfoByUid() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetBilibiliInfoByUid(::grpc::ServerContext* /*context*/, const ::vNerve::bilibili::GetBilibiliInfoByUidRequest* /*request*/, ::vNerve::bilibili::BilibiliInfo* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetBilibiliInfoByUid(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::vNerve::bilibili::GetBilibiliInfoByUidRequest,::vNerve::bilibili::BilibiliInfo>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_GetAllBilibiliInfos<WithStreamedUnaryMethod_GetBilibiliInfoByUid<Service > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_GetAllBilibiliInfos<WithStreamedUnaryMethod_GetBilibiliInfoByUid<Service > > StreamedService;
};

}  // namespace bilibili
}  // namespace vNerve


#endif  // GRPC_vNerve_2fbilibili_2fbilibili_5finfo_2eproto__INCLUDED
